<a href="https://colab.research.google.com/github/shabari0019/PyTorch_YT/blob/main/PT_0_0_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Thu Mar 13 16:47:02 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   60C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
print(torch.__version__)


2.5.1+cu124


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7,7,7])
vector

tensor([7, 7, 7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([4])

In [10]:
matrix = torch.tensor([[[[7,8],[5,8],[1,2]]]])
# matrix

# matrix[0][1]

matrix[0][0][2][1]

tensor(2)

In [11]:
#Random tensor
random_tensor = torch.rand(1,2,20)
len(random_tensor[0])

2

In [12]:
#Random tesnsor with similar shape to image tensor
random_image_tensor = torch.rand(size=(8,8,3))
random_image_tensor.shape, random_image_tensor.ndim
#random_image_tensor



(torch.Size([8, 8, 3]), 3)

In [13]:
#create tensor with all zeros

zeros = torch.zeros(size=(3,4))
zeros.dtype


ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
#creating a range of tensor and tensor-like
range = torch.arange(3,10)
range_zeros = torch.zeros_like(range )
range_zeros

tensor([0, 0, 0, 0, 0, 0, 0])

**# Datatype ='tensor.dtype',shape='tensor.shape',on right device = tensor.device comman errors we may encounter**


devices means where it runs like CUDA or CPU

whether to track gradients






In [15]:
f32 = torch.tensor([3.0,5.0,9.0],dtype = None,
                                device=None,
                  requires_grad=False)
#default data type in tensor is float
f32.dtype


torch.float32

In [16]:
#whenever we get datatype error

f16 = f32.type(torch.float16)

f16.dtype

torch.float16

In [17]:
f32*f16

tensor([ 9., 25., 81.])

In [18]:
int_32_tensor = torch.tensor([3,4,5],dtype = torch.int32)

f16*int_32_tensor

tensor([ 9., 20., 45.], dtype=torch.float16)

In [19]:
some_tensor = torch.rand(3,4)
changed = some_tensor.type(torch.int32)
print(some_tensor)

print(changed.dtype)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.1032, 0.6529, 0.1773, 0.2713],
        [0.8578, 0.9969, 0.0773, 0.9233],
        [0.5230, 0.1617, 0.1353, 0.6500]])
torch.int32
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


###manipulating tensors
Tensor operation
Addition
Substraction
Multiplication (elementwise)
Division
Matrix multiplation


In [20]:
tensor = torch.tensor([1,23,3])
tensor +10


tensor([11, 33, 13])

In [21]:
tensor*10
tensor-10


tensor([-9, 13, -7])

In [22]:
mul = torch.mul(tensor,10)
mul

tensor([ 10, 230,  30])

In [23]:
#matrix multiplication(dot product)

result = torch.matmul(torch.rand(3,1),torch.rand(1,4))
result.shape


torch.Size([3, 4])

In [24]:
tensor_a = torch.tensor([
    [1,2],
    [4,5],
    [5,9]]
)


tensor_b = torch.tensor([
    [6,9],
    [2,8],
    [7,1]]
)


tensor_a.shape

torch.Size([3, 2])

In [25]:
#to fix tensor shape issues we can manipulate

tensor_b.T
tensor_b.T.shape

torch.Size([2, 3])

In [26]:

mul_result = torch.matmul(tensor_a,tensor_b.T)
mul_result.shape


torch.Size([3, 3])

In [27]:
#finding min,max,sum,mean

x = torch.arange(0,100,10)

print(torch.min(x))

print(torch.max(x))

print(torch.sum(x))

print(torch.mean(x.type(torch.float32)))



tensor(0)
tensor(90)
tensor(450)
tensor(45.)


In [28]:
x.dtype

torch.int64

#Reshaping stacking squeezing and unsqueezing

*reshapes an input to a defined shape

*squeeze removes all 1 dimension from a tensor

*stacking combining multiple tensors on top of each other or side by side

In [29]:
import torch
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
#change the view

z = x.view(1,9)
z.shape

torch.Size([1, 9])

In [32]:
#changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0]=5
z,x


(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [33]:
#stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x,x],dim=1 ) #verticle stacking for horizontal stacking dim=0
x_stacked

tensor([[5, 5, 5, 5, 5],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9]])

In [34]:
#torch.squeeze() removes all single dimensions from a target tensor

x_reshaped.shape
x_squeezed = x_reshaped.squeeze()
x_squeezed.shape


torch.Size([9])

In [35]:
#unsqueeze


x_unsqueeze = x_squeezed.unsqueeze(dim=0)
x_unsqueeze.shape

torch.Size([1, 9])

In [36]:
#torch.permute actually used to rearrange the axis

image = torch.rand(size=(3,4,4))
image.shape

torch.Size([3, 4, 4])

In [37]:
image_permuted = image.permute(2,1,0)

image_permuted.shape

torch.Size([4, 4, 3])

In [38]:
image[0,0,0] = 0.1111


In [39]:
image

tensor([[[0.1111, 0.2834, 0.0877, 0.1772],
         [0.0638, 0.8947, 0.6051, 0.4741],
         [0.5838, 0.5813, 0.9742, 0.1194],
         [0.5860, 0.2301, 0.7690, 0.7317]],

        [[0.2263, 0.3199, 0.0264, 0.1157],
         [0.9768, 0.2470, 0.3045, 0.1930],
         [0.7213, 0.8560, 0.1917, 0.8181],
         [0.1487, 0.3793, 0.1795, 0.5883]],

        [[0.6548, 0.6000, 0.1777, 0.0236],
         [0.5985, 0.8387, 0.3577, 0.7539],
         [0.3728, 0.2506, 0.8138, 0.4027],
         [0.4187, 0.0887, 0.2568, 0.5093]]])

In [40]:
image_permuted

tensor([[[0.1111, 0.2263, 0.6548],
         [0.0638, 0.9768, 0.5985],
         [0.5838, 0.7213, 0.3728],
         [0.5860, 0.1487, 0.4187]],

        [[0.2834, 0.3199, 0.6000],
         [0.8947, 0.2470, 0.8387],
         [0.5813, 0.8560, 0.2506],
         [0.2301, 0.3793, 0.0887]],

        [[0.0877, 0.0264, 0.1777],
         [0.6051, 0.3045, 0.3577],
         [0.9742, 0.1917, 0.8138],
         [0.7690, 0.1795, 0.2568]],

        [[0.1772, 0.1157, 0.0236],
         [0.4741, 0.1930, 0.7539],
         [0.1194, 0.8181, 0.4027],
         [0.7317, 0.5883, 0.5093]]])

Indexing in tensor


In [41]:
#pytroch with numpy

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)#to convert torch data into numpy data
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [42]:
array.dtype,tensor.dtype #torch default dtype is float32 but num dtype is float 54


(dtype('float64'), torch.float64)

In [43]:
tensor.type(torch.float32).dtype

torch.float32

#reproducability (trying random out random values)

In [44]:
# to reduce the randomness in NN we use random seed
import torch
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)

print(random_tensor_a == random_tensor_b)

tensor([[0.3513, 0.3088, 0.3425, 0.6114],
        [0.6570, 0.7720, 0.5097, 0.3518],
        [0.5213, 0.3538, 0.4823, 0.3716]])
tensor([[0.7973, 0.3179, 0.3278, 0.3731],
        [0.8394, 0.4968, 0.7413, 0.9016],
        [0.1402, 0.4200, 0.1615, 0.9181]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [45]:
#random tensors but reproducable

RANDOM_SEED = 32
torch.manual_seed(RANDOM_SEED)#whenever we want to random seed use for each random called
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)

print(random_tensor_c == random_tensor_d)

tensor([[0.8757, 0.2721, 0.4141, 0.7857],
        [0.1130, 0.5793, 0.6481, 0.0229],
        [0.5874, 0.3254, 0.9485, 0.5219]])
tensor([[0.8757, 0.2721, 0.4141, 0.7857],
        [0.1130, 0.5793, 0.6481, 0.0229],
        [0.5874, 0.3254, 0.9485, 0.5219]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running tensors and pytorch objects on the gpu

In [46]:
!nvidia-smi

Thu Mar 13 16:47:10 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   59C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [47]:
import torch
torch.cuda.is_available()

True

In [48]:
#setup device agnostic code (run on gpu aste)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [49]:
#count numbers of GPU
torch.cuda.device_count()

1

In [50]:
tensor = torch.tensor([1,23,4],device = "cpu")
tensor.device

device(type='cpu')

In [51]:
#moving tensor to gpu if available
#numpy won't work on
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([ 1, 23,  4], device='cuda:0')