<a href="https://colab.research.google.com/github/shabari0019/PyTorch_YT/blob/main/PT_0_0_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
print(torch.__version__)


2.5.1+cu124


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7,7,7])
vector

tensor([7, 7, 7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([4])

In [ ]:
matrix = torch.tensor([[[[7,8],[5,8],[1,2]]]])
# matrix

# matrix[0][1]

matrix[0][0][2][1]

tensor(2)

In [ ]:
#Random tensor
random_tensor = torch.rand(1,2,20)
len(random_tensor[0])

2

In [ ]:
#Random tesnsor with similar shape to image tensor
random_image_tensor = torch.rand(size=(8,8,3))
random_image_tensor.shape, random_image_tensor.ndim
#random_image_tensor



(torch.Size([8, 8, 3]), 3)

In [ ]:
#create tensor with all zeros

zeros = torch.zeros(size=(3,4))
zeros.dtype


ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#creating a range of tensor and tensor-like
range = torch.arange(3,10)
range_zeros = torch.zeros_like(range )
range_zeros

tensor([0, 0, 0, 0, 0, 0, 0])

**# Datatype ='tensor.dtype',shape='tensor.shape',on right device = tensor.device comman errors we may encounter**


devices means where it runs like CUDA or CPU

whether to track gradients






In [ ]:
f32 = torch.tensor([3.0,5.0,9.0],dtype = None,
                                device=None,
                  requires_grad=False)
#default data type in tensor is float
f32.dtype


torch.float32

In [ ]:
#whenever we get datatype error

f16 = f32.type(torch.float16)

f16.dtype

torch.float16

In [ ]:
f32*f16

tensor([ 9., 25., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,4,5],dtype = torch.int32)

f16*int_32_tensor

tensor([ 9., 20., 45.], dtype=torch.float16)

In [ ]:
some_tensor = torch.rand(3,4)
changed = some_tensor.type(torch.int32)
print(some_tensor)

print(changed.dtype)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.7678, 0.6628, 0.6209, 0.2738],
        [0.7250, 0.3052, 0.2541, 0.2983],
        [0.2027, 0.0087, 0.8922, 0.9871]])
torch.int32
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


###manipulating tensors
Tensor operation
Addition
Substraction
Multiplication (elementwise)
Division
Matrix multiplation


In [ ]:
tensor = torch.tensor([1,23,3])
tensor +10


tensor([11, 33, 13])

In [ ]:
tensor*10
tensor-10


tensor([-9, 13, -7])

In [ ]:
mul = torch.mul(tensor,10)
mul

tensor([ 10, 230,  30])

In [ ]:
#matrix multiplication(dot product)

result = torch.matmul(torch.rand(3,1),torch.rand(1,4))
result.shape


torch.Size([3, 4])

In [ ]:
tensor_a = torch.tensor([
    [1,2],
    [4,5],
    [5,9]]
)


tensor_b = torch.tensor([
    [6,9],
    [2,8],
    [7,1]]
)


tensor_a.shape

torch.Size([3, 2])

In [ ]:
#to fix tensor shape issues we can manipulate

tensor_b.T
tensor_b.T.shape

torch.Size([2, 3])

In [ ]:

mul_result = torch.matmul(tensor_a,tensor_b.T)
mul_result.shape


torch.Size([3, 3])

In [ ]:
#finding min,max,sum,mean

x = torch.arange(0,100,10)

print(torch.min(x))

print(torch.max(x))

print(torch.sum(x))

print(torch.mean(x.type(torch.float32)))



tensor(0)
tensor(90)
tensor(450)
tensor(45.)


In [ ]:
x.dtype

torch.int64

#Reshaping stacking squeezing and unsqueezing

*reshapes an input to a defined shape

*squeeze removes all 1 dimension from a tensor

*stacking combining multiple tensors on top of each other or side by side

In [ ]:
import torch
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
#change the view

z = x.view(1,9)
z.shape

torch.Size([1, 9])

In [ ]:
#changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0]=5
z,x


(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
#stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x,x],dim=1 ) #verticle stacking for horizontal stacking dim=0
x_stacked

tensor([[5, 5, 5, 5, 5],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9]])

In [ ]:
#torch.squeeze() removes all single dimensions from a target tensor

x_reshaped.shape
x_squeezed = x_reshaped.squeeze()
x_squeezed.shape


torch.Size([9])

In [ ]:
#unsqueeze


x_unsqueeze = x_squeezed.unsqueeze(dim=0)
x_unsqueeze.shape

torch.Size([1, 9])

In [ ]:
#torch.permute actually used to rearrange the axis

image = torch.rand(size=(3,4,4))
image.shape

torch.Size([3, 4, 4])

In [ ]:
image_permuted = image.permute(2,1,0)

image_permuted.shape

torch.Size([4, 4, 3])

In [ ]:
image[0,0,0] = 0.1111


In [ ]:
image

tensor([[[0.1111, 0.3793, 0.1111, 0.2335],
         [0.4376, 0.3111, 0.2425, 0.3907],
         [0.6354, 0.9514, 0.0525, 0.5734],
         [0.9238, 0.7113, 0.2398, 0.0203]],

        [[0.7280, 0.6255, 0.8466, 0.6288],
         [0.9468, 0.8849, 0.1413, 0.4546],
         [0.0223, 0.0334, 0.7661, 0.5312],
         [0.6511, 0.7816, 0.8258, 0.7016]],

        [[0.4122, 0.0311, 0.9411, 0.3359],
         [0.5949, 0.2778, 0.9473, 0.3054],
         [0.0200, 0.1552, 0.5562, 0.1391],
         [0.2008, 0.5915, 0.3605, 0.5103]]])

In [ ]:
image_permuted

tensor([[[0.1111, 0.7280, 0.4122],
         [0.4376, 0.9468, 0.5949],
         [0.6354, 0.0223, 0.0200],
         [0.9238, 0.6511, 0.2008]],

        [[0.3793, 0.6255, 0.0311],
         [0.3111, 0.8849, 0.2778],
         [0.9514, 0.0334, 0.1552],
         [0.7113, 0.7816, 0.5915]],

        [[0.1111, 0.8466, 0.9411],
         [0.2425, 0.1413, 0.9473],
         [0.0525, 0.7661, 0.5562],
         [0.2398, 0.8258, 0.3605]],

        [[0.2335, 0.6288, 0.3359],
         [0.3907, 0.4546, 0.3054],
         [0.5734, 0.5312, 0.1391],
         [0.0203, 0.7016, 0.5103]]])

Indexing in tensor


In [2]:
#pytroch with numpy

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)#to convert torch data into numpy data
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [4]:
array.dtype,tensor.dtype #torch default dtype is float32 but num dtype is float 54


(dtype('float64'), torch.float64)

In [6]:
tensor.type(torch.float32).dtype

torch.float32

#reproducability (trying random out random values)

In [14]:
# to reduce the randomness in NN we use random seed
import torch
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)

print(random_tensor_a == random_tensor_b)

tensor([[4.0529e-01, 7.4810e-01, 9.2125e-01, 6.8482e-01],
        [4.0826e-01, 2.3972e-01, 7.9727e-04, 6.7108e-01],
        [8.6409e-01, 9.3886e-01, 4.9022e-01, 7.2912e-01]])
tensor([[0.5192, 0.7276, 0.3792, 0.3283],
        [0.9010, 0.6672, 0.5574, 0.3871],
        [0.0658, 0.7406, 0.9723, 0.3783]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [16]:
#random tensors but reproducable

RANDOM_SEED = 32
torch.manual_seed(RANDOM_SEED)#whenever we want to random seed use for each random called
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)

print(random_tensor_c == random_tensor_d)

tensor([[0.8757, 0.2721, 0.4141, 0.7857],
        [0.1130, 0.5793, 0.6481, 0.0229],
        [0.5874, 0.3254, 0.9485, 0.5219]])
tensor([[0.8757, 0.2721, 0.4141, 0.7857],
        [0.1130, 0.5793, 0.6481, 0.0229],
        [0.5874, 0.3254, 0.9485, 0.5219]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running tensors and pytorch objects on the gpu

In [1]:
!nvidia-smi

Wed Mar 12 17:27:42 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
#setup device agnostic code (run on gpu aste)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#count numbers of GPU
torch.cuda.device_count()

1